# Generated by Django 5.2.6 on 2025-12-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('modele', models.CharField(max_length=255)),
                ('objet_id', models.CharField(blank=True, max_length=50, null=True)),
                ('document_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('ancienne_valeur', models.JSONField(blank=True, null=True)),
                ('nouvelle_valeur', models.JSONField(blank=True, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_phase', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orde', models.IntegerField()),
                ('procedure', models.CharField(max_length=90, null=True)),
                ('document_procedure', models.BinaryField(null=True)),
                ('document_travail_valide', models.BinaryField(null=True)),
            ],
        ),
    ]
