# Generated by Django 5.2.6 on 2025-11-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure', models.CharField(max_length=255)),
                ('Document_de_procedure_a_suivre', models.BinaryField()),
                ('document_de_travail', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
