# Generated by Django 5.2.6 on 2025-11-17 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_phase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='Document_de_procedure_a_suivre',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='document_de_travail',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='procedure',
        ),
        migrations.AddField(
            model_name='phase',
            name='nom_phase',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orde', models.IntegerField()),
                ('Document_procedure', models.BinaryField(null=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='audit.phase')),
            ],
        ),
    ]
