# Generated by Django 5.2.6 on 2025-11-17 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_remove_phase_document_de_procedure_a_suivre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedure',
            old_name='Document_procedure',
            new_name='document_procedure',
        ),
    ]
