# Generated by Django 5.2.6 on 2025-11-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_rename_document_procedure_procedure_document_procedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='document_travail_valide',
            field=models.BinaryField(null=True),
        ),
    ]
