# Generated by Django 5.2.6 on 2025-11-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_procedure_document_travail_valide'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='procedure',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
