<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-11-04 10:13
=======
# Generated by Django 5.2.6 on 2025-09-29 20:53
>>>>>>> data

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Archivage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=10, null=True)),
                ('contenu', models.BinaryField(null=True)),
                ('date_arrivee', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('exercice', models.CharField(max_length=10, null=True)),
                ('mois', models.CharField(max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_piece', models.CharField(max_length=20)),
                ('periode', models.CharField(max_length=30)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
=======
            name='PieceComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('periode', models.CharField(max_length=30)),
>>>>>>> data
            ],
        ),
    ]
