# Generated by Django 5.2.6 on 2025-12-19 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='poste_comptable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.poste_comptable'),
        ),
        migrations.AddField(
            model_name='archivage',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='data.document'),
        ),
        migrations.AddField(
            model_name='piece',
            name='poste_comptable',
            field=models.ManyToManyField(related_name='piece_comptables', to='users.poste_comptable'),
        ),
        migrations.AddField(
            model_name='document',
            name='piece',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='piece_document', to='data.piece'),
        ),
    ]
