# Generated by Django 5.2.6 on 2025-11-04 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Archivage',
        ),
    ]
