# Generated by Django 5.2.6 on 2025-11-04 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_delete_archivage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archivage', to='data.document')),
            ],
        ),
    ]
