# Generated by Django 5.2.6 on 2025-11-10 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_archivage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivage',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='data.document'),
        ),
    ]
